name: nodeserver

services:
  server:
    build:
      dockerfile: Dockerfile_app
      context: .
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build:
      dockerfile: Dockerfile_db
      context: .
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
