FROM postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD "postgres"
ENV POSTGRES_DB typer
EXPOSE 5432 

# .env file

# PORT=3000
# DB_NAME=typer
# DB_USER="postgres"
# DB_PASSWORD="postgres"
# DB_HOST=localhost
# DB_PORT=5432

