FROM postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB summer_school
EXPOSE 5432 

# .env file

# PORT=3000
# DB_NAME=summer_school
# DB_USER="postgres"
# DB_PASSWORD=""
# DB_HOST=localhost
# DB_PORT=5432

